# Generated by Django 4.1 on 2024-01-08 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("manage_emojis", "0001_initial"),
        ("chatrooms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="emoji",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="manage_emojis.emoji",
            ),
        ),
    ]
