# Generated by Django 5.0.1 on 2024-01-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0003_chatroom_creator_alter_chatroom_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='message',
            name='emoji',
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
