# Generated by Django 5.0.1 on 2024-01-12 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0004_alter_message_options_remove_message_emoji_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='deleted_messages',
            field=models.ManyToManyField(related_name='deleted_in_chatrooms', to='chatrooms.message'),
        ),
    ]
